# Calculating Power-law scaling in fluctuations of information

In [1]:
import os
import numpy as np
import pandas as pd
from scipy.stats import t

import pyarrow.parquet as pq
from tqdm.notebook import tqdm
import warnings;warnings.filterwarnings('ignore')

In [2]:
CORPUS_NAME = ''

In [3]:
# DATA_PATH = '/Volumes/Data-Repo/shapeoflang3/AF/obs'
DATA_PATH = '../../../updated-data/obs'
NULL_DATA_PATH = '../../../updated-data/null'

OUTPUTS_PATH = 'reports'
if not os.path.exists(OUTPUTS_PATH):
    os.mkdir(OUTPUTS_PATH)

In [4]:
def grab_all_files(PATH, file_type='.parquet'):
    files = [
        [
            os.path.join(root, f) for f in files
            if f.endswith(file_type) and (not f.startswith('.'))
        ]
        for root, _, files in os.walk(PATH)
    ]
    return sum(files, [])

def lang_id(x):
    if 'xling-' in x:
        return x.split('-')[2]
    else:
        return 'eng'

def corpus_id(x):
    if 'xling-' in x:
        return x.split('-')[1]
    else:
        return x.split('-')[0]

In [5]:
fs = [
    f for f in os.listdir(DATA_PATH)
    if ('xling-' not in f)
    and (not f.startswith('.'))
    and (f.endswith('.parquet'))
    and (CORPUS_NAME in f)
]
len(fs)

4462

## Processing individual datasets

In [6]:
# formula = '{} ~ nx + ny + self'.format(COEF_VAR)

In [7]:
COEF_VAR = 'avar'

In [8]:
time_col = 'mtau'
# time_col = 'n'

In [9]:
df_scale, df_regression, k_docs, error_tracker = [], [], dict(), 0

for f in tqdm(fs):
    # print('===][===')
    # print(f.split('/')[-1])

    table = pq.ParquetFile(os.path.join(DATA_PATH, f))

    df = table.read().to_pandas()
    df['self'] = df['x_speaker'] == df['y_speaker']
    df[COEF_VAR] = df[COEF_VAR] #/ df['n']

    # df['mtau'] = (df['min_y_turn_id'] + df['mtau']) - df['x_turn_id']
    # df[COEF_VAR] = np.sqrt(df[COEF_VAR])
    groups = df.groupby(by=['x_speaker', 'y_speaker'])
    # groups = df.groupby(by=['x_turn_id', 'y_speaker'])
    for labels, dfi in groups:
        self_other = dfi['self'].unique()[0]
        # dfi['min_y_turn_id'] = dfi.groupby('x_turn_id')['y_turn_id'].transform('min')

        av = dfi[COEF_VAR].values
        mtau = dfi[time_col].values

        sel = (av > 0) & (mtau > 1)

        try:
            if sel.sum() > 1:

                b, a = np.polyfit(
                    np.log(mtau[sel]),
                    np.log(av[sel]),
                    1
                )

                df_regression += [
                    {
                        'corpus': corpus_id(f),
                        'cid': f.replace('.parquet', ''),
                        'speaker': labels[0],
                        'self': self_other,
                        'a': np.exp(a),
                        'b': b,
                        'k': len(dfi)
                    }
                ]

        except Exception:
            error_tracker += 1

df_regression = pd.DataFrame(df_regression)

  0%|          | 0/4462 [00:00<?, ?it/s]

In [10]:
df_regression.isna().mean()

corpus     0.0
cid        0.0
speaker    0.0
self       0.0
a          0.0
b          0.0
k          0.0
dtype: float64

In [11]:
np.isinf(df_regression['b']).mean()

np.float64(0.0)

In [12]:
# df_regression = df_regression.loc[
#     (df_regression.isna().astype(int).sum(axis=1) == 0)
#     & (np.isinf(df_regression).astype(int).sum(axis=1) == 0)
# ]

In [13]:
df_regression.to_parquet(
    os.path.join(OUTPUTS_PATH,'all.parquet'),
    compression='snappy', engine='fastparquet'
)

## Corpus level analysis of results

In [15]:
split_by = ['corpus', 'self']

In [16]:
df0 = df_regression[split_by+['b']].groupby(by=split_by).agg('mean').reset_index()
df0['std'] = df_regression[split_by+['b']].groupby(by=split_by).agg('std').reset_index()['b'].values

# df0['k'] = [k_docs[corpus][s] for corpus, s in df0[['corpus', 'self']].values]
df0['k'] = df_regression[split_by+['b']].groupby(by=split_by).agg('count').reset_index()['b'].values

df0['se'] = df0['std'] / np.sqrt(df0['k'])

In [17]:
df0['t'] = df0['b'] / df0['se']
df0['p'] = [t.sf(tstat.__abs__(), df=k-1) for tstat, k in df0[['t', 'k']].values]

In [18]:
df0.head(n=50)

,corpus,self,b,std,k,se,t,p
0,CABNC,False,0.551217,0.464442,12291,0.004189,131.578329,0.000000e+00
1,CABNC,True,0.549612,0.603463,4446,0.009050,60.728136,0.000000e+00
2,CANDOR,False,0.786530,0.031083,3304,0.000541,1454.510240,0.000000e+00
3,CANDOR,True,0.846892,0.083651,3304,0.001455,581.936742,0.000000e+00
4,CORAAL,False,0.737195,0.186471,699,0.007053,104.522367,0.000000e+00
5,CORAAL,True,0.779307,0.390184,569,0.016357,47.642548,7.234605e-201
6,DISPEL,False,0.691891,0.180099,38,0.029216,23.681920,2.964941e-24
7,DISPEL,True,0.681831,0.099076,37,0.016288,41.860892,1.964686e-32
8,Frederiksen,False,0.628169,0.078625,4,0.039312,15.978921,2.665070e-04
9,Frederiksen,True,0.701568,0.071331,4,0.035666,19.670702,1.435342e-04
10,GCSAusE,False,0.592669,0.185411,206,0.012918,45.878548,4.488329e-110
11,GCSAusE,True,0.646393,0.135541,105,0.013227,48.867518,7.334200e-74
12,Graesser,False,0.687510,0.035935,6,0.014670,46.863533,4.178134e-08
13,Graesser,True,0.722011,0.039442,6,0.016102,44.840040,5.207538e-08
14,MICASE,False,0.471973,0.517480,11292,0.004870,96.919088,0.000000e+00
15,MICASE,True,0.461279,0.389611,1101,0.011742,39.284914,6.049309e-212
16,SBCSAE,False,0.562348,0.382510,1428,0.010122,55.555457,0.000000e+00
17,SBCSAE,True,0.690827,1.371811,256,0.085738,8.057400,1.506396e-14
18,SCoSE,False,0.603494,0.364494,150,0.029761,20.278152,5.374182e-45
19,SCoSE,True,0.581387,0.261855,70,0.031298,18.576041,7.405512e-29
20,callfriend,False,0.779622,0.142960,123,0.012890,60.481408,4.025249e-93
21,callfriend,True,0.738706,0.160788,90,0.016949,43.585273,3.948842e-62
22,callhome,False,0.715670,0.180664,410,0.008922,80.210667,1.261329e-252
23,callhome,True,0.738866,0.124857,358,0.006599,111.968023,1.898389e-280
24,grace,False,0.790171,0.046495,146,0.003848,205.346398,6.319437e-181
25,grace,True,0.802740,0.059579,140,0.005035,159.419947,1.416629e-159
26,med_school,False,0.384317,0.463487,77,0.052819,7.276082,1.320444e-10
27,med_school,True,0.422292,0.068191,12,0.019685,21.452376,1.258053e-10

In [19]:
df0.to_csv(
    os.path.join(OUTPUTS_PATH, 'corpus-results.csv'),
    index=False, encoding='utf-8'
)

## Aggregate analysis

In [20]:
split_by = ['self']

In [21]:
df0 = df_regression[split_by+['b']].groupby(by=split_by).agg('mean').reset_index()
df0['std'] = df_regression[split_by+['b']].groupby(by=split_by).agg('std').reset_index()['b'].values
df0['k'] = df_regression[split_by+['b']].groupby(by=split_by).agg('count').reset_index()['b'].values

# df0['k'] = [k_docs[corpus][s] for corpus, s in df0[['corpus', 'self']].values]

df0['se'] = df0['std'] / np.sqrt(df0['k'])

In [22]:
df0['t'] = df0['b'] / df0['se']
df0['p'] = [t.sf(tstat.__abs__(), df=k-1) for tstat, k in df0[['t', 'k']].values]

In [23]:
df0.head(n=20)

    self         b       std      k        se           t    p
0  False  0.556816  0.456155  30174  0.002626  212.039310  0.0
1   True  0.662910  0.499473  10498  0.004875  135.986569  0.0

In [24]:
df0.to_csv(
    os.path.join(OUTPUTS_PATH, 'agg-results.csv'),
    index=False,
    encoding='utf-8'
)